# Generated by Django 4.2.6 on 2023-11-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgementReceived',
            fields=[
                ('A_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('R_ID', models.IntegerField(null=True)),
                ('MsgFile', models.BinaryField(max_length='max')),
            ],
        ),
        migrations.CreateModel(
            name='AcknowledgementRequest',
            fields=[
                ('R_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CNR_ID', models.IntegerField(null=True)),
                ('Status', models.BooleanField()),
                ('CreatedDate', models.DateTimeField()),
                ('SendDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditNoteResumeEmail',
            fields=[
                ('CNR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CN_ID', models.CharField(max_length=10)),
                ('DateIssued', models.DateTimeField()),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Body', models.TextField()),
                ('Subject', models.CharField(max_length=40)),
                ('Status', models.BooleanField()),
                ('IsValid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CN_ID', models.CharField(max_length=20, unique=True)),
                ('D_ID', models.CharField(max_length=10)),
                ('TotalDocumentAmount', models.DecimalField(decimal_places=20, max_digits=38)),
                ('TotalVATAmountDocumentt', models.DecimalField(decimal_places=20, max_digits=38)),
                ('TotalDocumentAmountWithVAT', models.DecimalField(decimal_places=20, max_digits=38)),
                ('AccountingNumberID', models.CharField(max_length=30)),
                ('IssuedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_ID', models.CharField(max_length=10, unique=True)),
                ('DealerName', models.CharField(max_length=100)),
                ('DealerVATnumber', models.CharField(max_length=20)),
                ('DealerEmail', models.CharField(max_length=80)),
                ('CreatedDate', models.DateTimeField()),
                ('ModifiedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'Dealers',
            },
        ),
    ]
