# Generated by Django 4.2.6 on 2024-05-02 08:56

import dashboard.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgementReceived',
            fields=[
                ('A_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('R_ID', models.IntegerField(null=True)),
                ('MsgFile', models.BinaryField(max_length='max')),
            ],
            options={
                'db_table': 'AcknowledgementReceived',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcknowledgementRequest',
            fields=[
                ('R_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CNR_ID', models.IntegerField(null=True)),
                ('Status', models.BooleanField()),
                ('CreatedDate', models.DateTimeField()),
                ('SendDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'AcknowledgementRequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNoteResumeEmail',
            fields=[
                ('CNR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CN_ID', models.CharField(max_length=10)),
                ('DateIssued', models.DateTimeField()),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Body', models.TextField()),
                ('Subject', models.CharField(max_length=40)),
                ('Status', models.BooleanField()),
                ('IsValid', models.BooleanField()),
            ],
            options={
                'db_table': 'CreditNoteResumeEmail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNotes',
            fields=[
                ('CN_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('TotalDocumentAmount', models.DecimalField(decimal_places=20, max_digits=38)),
                ('TotalVATAmountDocumentt', models.DecimalField(decimal_places=20, max_digits=38)),
                ('TotalDocumentAmountWithVAT', models.DecimalField(decimal_places=20, max_digits=38)),
                ('AccountingNumberID', models.CharField(max_length=30)),
                ('IssuedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'CreditNotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('D_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[dashboard.validations.validate_d_id])),
                ('DealerName', models.CharField(max_length=100)),
                ('DealerVATnumber', models.CharField(max_length=20)),
                ('DealerEmail', models.EmailField(max_length=80)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Dealers',
                'managed': False,
            },
        ),
    ]
