# Generated by Django 4.2.6 on 2024-05-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acknowledgementreceived',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='acknowledgementrequest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='creditnoteresumeemail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='creditnotes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dealers',
            options={'managed': True},
        ),
    ]
