# Generated by Django 4.2.6 on 2024-05-10 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnoteresumeemail',
            name='CNR_ID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='creditnoteresumeemail',
            name='CN_ID',
            field=models.ForeignKey(db_column='CN_ID', on_delete=django.db.models.deletion.CASCADE, to='dashboard.creditnotes'),
        ),
        migrations.AlterField(
            model_name='creditnotes',
            name='IssuedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
