# Generated by Django 4.2.6 on 2024-02-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='ModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
