# Generated by Django 4.2.6 on 2024-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_creditnoteresumeemail_cnr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotes',
            name='IssuedDate',
            field=models.DateTimeField(),
        ),
    ]
