# Generated by Django 4.2.6 on 2024-04-22 16:15

import dashboard.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dealers_createddate_alter_dealers_modifieddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='D_ID',
            field=models.CharField(max_length=10, unique=True, validators=[dashboard.validations.validate_d_id]),
        ),
        migrations.AlterField(
            model_name='dealers',
            name='DealerEmail',
            field=models.EmailField(max_length=80),
        ),
    ]
