# Generated by Django 4.2.6 on 2024-05-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_creditnotes_issueddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnoteresumeemail',
            name='DateIssued',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creditnoteresumeemail',
            name='IsValid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='creditnoteresumeemail',
            name='Month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='creditnoteresumeemail',
            name='Year',
            field=models.PositiveIntegerField(),
        ),
    ]
