# Generated by Django 4.2.6 on 2024-05-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_creditnoteresumeemail_dateissued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acknowledgementrequest',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='creditnoteresumeemail',
            name='Body',
        ),
        migrations.RemoveField(
            model_name='creditnoteresumeemail',
            name='CN_ID',
        ),
        migrations.RemoveField(
            model_name='creditnoteresumeemail',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='creditnoteresumeemail',
            name='Subject',
        ),
        migrations.AddField(
            model_name='acknowledgementrequest',
            name='RemindersSent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditnotes',
            name='CNR_ID',
            field=models.ForeignKey(blank=True, db_column='CNR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.creditnoteresumeemail'),
        ),
        migrations.AlterField(
            model_name='acknowledgementreceived',
            name='R_ID',
            field=models.ForeignKey(db_column='R_ID', default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.acknowledgementrequest'),
        ),
        migrations.AlterField(
            model_name='acknowledgementrequest',
            name='CNR_ID',
            field=models.ForeignKey(db_column='CNR_ID', default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.creditnoteresumeemail'),
        ),
        migrations.AlterField(
            model_name='acknowledgementrequest',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementrequest',
            name='R_ID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
