# Generated by Django 4.2.6 on 2024-05-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_acknowledgementrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='D_ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
