# Generated by Django 4.2.6 on 2024-06-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_dealers_d_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditNoteResumeEmail',
            new_name='CreditNoteResume',
        ),
        migrations.AlterModelTable(
            name='creditnoteresume',
            table='CreditNoteResume',
        ),
    ]
