# Generated by Django 4.2.6 on 2024-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_creditnoteresumeemail_creditnoteresume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnoteresume',
            name='Month',
        ),
        migrations.RemoveField(
            model_name='creditnoteresume',
            name='Year',
        ),
        migrations.AddField(
            model_name='acknowledgementrequest',
            name='EmailMessage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='creditnoteresume',
            name='TotalCreditNotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditnoteresume',
            name='TotalDocumentAmounts',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=38),
        ),
        migrations.AddField(
            model_name='creditnoteresume',
            name='TotalDocumentAmountsWithVAT',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=38),
        ),
        migrations.AddField(
            model_name='creditnoteresume',
            name='TotalVATAmounts',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=38),
        ),
    ]
